-- Backup generado automáticamente por export-backup.js
-- Fecha: 2026-08-11T20:14:42.166Z
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Desactivar verificación de llaves foráneas durante el restore
SET session_replication_role = 'replica';

-- Datos para la tabla: Citas (1 registros)
INSERT INTO "Citas" ("id", "libro_id", "texto", "pagina", "comentario") VALUES (1, 1, '🛠️ Cómo cargar cada ítem (Paso a Paso)
Para que el sistema automatice todo sin fallas, debés estructurar y dictar los datos de la siguiente manera:

1. Posicionamiento SEO
Cómo entenderlo: Es una tarea/servicio continuo que 24on le presta a Jordan.

Cómo cargarlo: Debes crear un Proyecto llamado "SEO Jordan" vinculado a la entidad Jordan.

Las Tareas: Dentro de ese proyecto, las tareas urgentes (ej: "Indexar URLs en Search Console") se guardan ahí.

El truco de la visión global: Como el proyecto "SEO Jordan" pertenece a la entidad Jordan, y Jordan es cliente de 24on, el backend mapeará automáticamente que esa tarea pendiente también aparezca en el panel de control de 24on bajo la categoría "Tareas urgentes de clientes".

2. Sistema de gestión (jordan.24on.com.py)
Cómo entenderlo: Es un producto de software desarrollado por tu agencia, alojado en un subdominio tuyo pero operado por el cliente.

Cómo cargarlo: Creá el Proyecto "Sistema de Gestión Jordan" enlazado a Jordan.

Los Enlaces (Links): En la sección de enlaces del Drawer de este proyecto, pegá la URL https://jordan.24on.com.py. Así, el nodo del proyecto en el grafo de Obsidian tendrá un hilo directo al enlace web. Cualquier tarea de mantenimiento de código o actualización de base de datos va a parar a este bloque.

3. Cobro anual (Hosting, Dominio y Mantenimiento de jordan.com.py)
Cómo entenderlo: Esto es puramente Finanzas, pero con un disparador temporal (Vencimiento).

Cómo cargarlo: Usá el nuevo menú global del espacio vacío y seleccioá Finanzas.

La estructura del comando: "Cargar finanza de tipo Cobro Anual por Gs. X.XXX.XXX para el Proyecto Mantenimiento Jordan, con vencimiento el [Fecha de Julio u otro mes]".

El impacto: El sistema creará el registro financiero, le asociará un recordatorio en la sección de Tareas Pendientes/Vencimientos, y enlazará ambos al nodo MES correspondiente. Cuando revises Julio en el cerebro, verás este cobro flotando al lado de los demás.

4. Venta de Equipo (PC de Escritorio para Darío)
Cómo entenderlo: Es una finanza de dos partes (un cobro parcial y un saldo agendado) vinculada directamente a una persona (Darío Ovelar).

Cómo cargarlo: Aquí es donde la flexibilidad del sistema brilla. No lo cargues en la empresa Jordan, cárgalo directamente en el nodo de la persona Darío Ovelar.

La estructura del comando: 1. Registrá el cobro del 50% ya realizado como CONCLUIDO.
2. Registrá el saldo restante como un nuevo registro financiero PENDIENTE, activando el toggle de "Programar Alerta de Vencimiento" con la fecha exacta que pactaste con él.

El impacto: Al estar vinculado a Darío, el grafo conectará el saldo pendiente con su nodo personal, pero como Darío está vinculado a Jordan, la deuda se reflejará de forma indirecta en el balance del cliente sin mezclarse con los servicios de desarrollo web de la agencia.

🚀 Resumen del Flujo de Trabajo diario
Cuando vayas a cargar algo nuevo por texto o voz, acostúmbrate a usar esta estructura jerárquica en tu frase:

"[Acción] + [Concepto] + [Proyecto/Cliente] + [Fecha/Monto si aplica]"

Ejemplo de voz para Gemini: "Agregar tarea urgente de actualización de servidor para el Sistema de Gestión de Jordan para este lunes."

Ejemplo de texto para DeepSeek: "Cargar gasto de Gs 150.000 por compra de insumos para el proyecto SEO Jordan."', NULL, NULL);
SELECT setval(pg_get_serial_sequence('"Citas"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "Citas";

-- Datos para la tabla: Entidades (11 registros)
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (12, 'Dario Ovelar', 'PERSONA', '{"alias":["tio dario","dario","tio"]}'::jsonb, NULL, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (13, 'Fabio Cino', 'PERSONA', '{"alias":["fabio","cino"]}'::jsonb, NULL, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (16, 'Bauel Top', 'EMPRESA', '{"alias":["bauel","baueltop.com.py"]}'::jsonb, NULL, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (18, 'Batical', 'EMPRESA', '{"alias":["batical.com.py","batical"]}'::jsonb, NULL, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (20, 'Ventas de Paraguay', 'EMPRESA', '{"alias":["ventasdeparaguay.com","ventas de paraguay","amazon paraguay"]}'::jsonb, NULL, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (21, 'ACV GROUP', 'EMPRESA', '{}'::jsonb, 14, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (11, 'Xavier Reyes', 'PERSONA', '{"alias":["yo","propietario","xavier"],"is_destacado":false}'::jsonb, NULL, TRUE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (19, 'Nix Cronicas', 'EMPRESA', '{"alias":["nix","nixmatic","nix chronicles","canal de youtube","youtube"],"is_destacado":false}'::jsonb, NULL, TRUE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (14, '24on Agency', 'EMPRESA', '{"alias":["agencia","24on.com.py","24on system"],"is_destacado":true}'::jsonb, 11, TRUE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (17, 'HyG S.A.', 'EMPRESA', '{"alias":["hygsa","hygsa.com.py","hyg"]}'::jsonb, 13, FALSE);
INSERT INTO "Entidades" ("id", "nombre", "tipo", "metadatos", "entidad_padre_id", "is_destacado") VALUES (22, 'JD Importador', 'EMPRESA', '{}'::jsonb, 14, FALSE);
SELECT setval(pg_get_serial_sequence('"Entidades"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "Entidades";

-- Datos para la tabla: Libros (1 registros)
INSERT INTO "Libros" ("id", "titulo", "autor", "estado_lectura", "veces_leido", "url_pdf", "creado_en", "tipo_media") VALUES (1, 'Notas Libres', 'Segundo Cerebro', 'LEIDO', 0, NULL, '2026-06-14T04:10:24.161Z', 'LIBRO');
SELECT setval(pg_get_serial_sequence('"Libros"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "Libros";

-- Datos para la tabla: Vinculos (9 registros)
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (8, 'PROPIETARIO_DE', 11, 14);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (9, 'PROPIETARIO_DE', 11, 19);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (10, 'PROPIETARIO_DE', 11, 20);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (11, 'TIO_DE', 12, 11);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (13, 'PROPIETARIO_DE', 13, 16);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (14, 'PROPIETARIO_DE', 13, 17);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (15, 'PROPIETARIO_DE', 13, 18);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (17, 'PROVEEDOR_DE', 14, 16);
INSERT INTO "Vinculos" ("id", "tipo", "origen_id", "destino_id") VALUES (18, 'PROVEEDOR_DE', 14, 17);
SELECT setval(pg_get_serial_sequence('"Vinculos"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "Vinculos";

-- Datos para la tabla: _prisma_migrations (2 registros)
INSERT INTO "_prisma_migrations" ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count") VALUES ('0f186659-61c2-4886-b14a-39650089f934', '54866adddbd8075cdba17506ef051e5736ed3c7444d8693d3bf278ddeeb4560d', '2026-06-13T07:46:16.837Z', '20260613074616_add_entidades_y_vinculos', NULL, NULL, '2026-06-13T07:46:16.520Z', 1);
INSERT INTO "_prisma_migrations" ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count") VALUES ('dfcf11a1-bbc0-4152-958b-d22777cde2b0', '1981f0dd9c833f69645dba2948b76e396ec391f58c15bf073f535f9e9fbb7ed2', '2026-06-13T19:04:52.172Z', '20260613190452_add_modulo_lectura', NULL, NULL, '2026-06-13T19:04:52.059Z', 1);
SELECT setval(pg_get_serial_sequence('"_prisma_migrations"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "_prisma_migrations";

-- Datos para la tabla: enlaces (40 registros)
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (1, 'https://clipdrop.co/image-upscaler', 'escalar imágenes, eliminar fondos, ', 'OTROS', ARRAY[], TRUE, '2026-06-26T05:04:06.115Z', NULL, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (2, 'https://clipdrop.co/image-upscaler', 'Clipdrop - Escalar imagenes, eliminar fondos con IA', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T05:29:36.347Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (3, 'https://www.micvideal.es/crear-cv/section/educ/2bbd2ddb-55c9-4935-ba92-bb7a6a74c085', 'Curriculum Xavi Editable', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T05:42:08.537Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (4, 'https://goon.feji.io/blog/desaparecio-en-1876-la-encontraron-en-1901-oculta-por-un-monstruo-mydieu', 'Nix Cronicas - Historia ', 'CONTENIDO_YOUTUBE', ARRAY[], TRUE, '2026-06-26T05:42:35.943Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (5, 'https://suno.com/discover', 'Suno - Crear canciones con IA', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T05:43:00.875Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (6, 'https://www.youtube.com/watch?v=0_Vidi1Z9cw', 'CPF Brasil online', 'TUTORIALES', ARRAY[], TRUE, '2026-06-26T05:56:30.701Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (7, 'https://tiendacecotec.com.py/categoria-producto/cocina/electrodomesticos/envasadoras-al-vacio/', 'Envasadora al Vacio', 'Productos de Reventa', ARRAY[], TRUE, '2026-06-26T06:20:23.653Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (8, 'https://www.google.com/u/1/recaptcha/admin/site/750965560/setup', 'recaptcha', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:20:44.446Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (9, 'https://www.google.com/search?sxsrf=APpeQnsln5gKfS8FZY7WPG7Ea34C6xHHZQ:1782110053498&q=Salvia+divinorum', 'Salvia planta medicinal', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:21:20.917Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (10, 'https://labs.google.com/pomelli/about/', 'Pomelli crea publicaciones en RRSS desde el link de una web', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:21:52.067Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (11, 'https://www.canva.com/folder/uploads', 'Canva editar catalogo nelore', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:22:22.401Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (12, 'https://www.facebook.com/marketplace/asuncion/search/?query=crema%20hinds', 'Crema hinds para mama', 'Productos de Reventa', ARRAY[], TRUE, '2026-06-26T06:22:52.934Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (13, 'https://www.puntofarma.com.py/producto/250187/crema-aclarante-pigmentbio-sensitive-areas-bioderma-cont.75-ml', 'Punto farma crema aclarante', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:24:13.389Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (14, 'https://paletadecolores.online/azul/celeste/', 'Paleta de colores Miss y Teen Argentina', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:24:36.491Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (15, 'https://www.laribera.com.py/', 'Sol naciente barrio 1', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:25:39.994Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (16, 'https://www.villadelparque.com.py/', 'sol naciente barrio 2', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:25:54.207Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (17, 'https://www.izara.com.py/', 'sol naciente barrio 3', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:26:08.378Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (18, 'https://rialto.com.py/', 'sol naciente barrio 4', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:26:21.342Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (19, 'https://sunsetvillage.com.py/', 'sol naciente barrio 5', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:26:33.811Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (20, 'https://www.bosquelago.com.py/', 'sol naciente barrio 6', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:26:55.832Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (21, 'https://cresia.com.py/', 'sol naciente barrio 7', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:27:12.828Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (22, 'file:///C:/Users/deste/Downloads/Mapa%20Solnaciente.pdf', 'sol naciente mapa local ', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:27:39.084Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (23, 'https://www.callmebot.com/es/blog/api-gratis-mensajes-whatsapp/', 'Callmebot Whatsapp', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:28:02.041Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (24, 'https://www.amplify.com.py/', 'publicitaria idea para oblicua hector', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:28:28.704Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (25, 'https://jwf.com.py/ooh-media/', 'oblicua idea 2', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:28:53.919Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (26, 'https://kingpublicidad.com.ar/', 'oblicua idea 3', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:29:07.489Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (27, 'https://sarmiento.net/', 'oblicua idea 4', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:29:21.371Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (28, 'https://duarteviapublica.com/', 'oblicua idea 5', 'OTROS', ARRAY[], TRUE, '2026-06-26T06:29:36.248Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (29, 'http://localhost:5050/login', 'php pg admin', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:30:06.412Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (30, 'https://es.aliexpress.com/item/1005011747660895.html?spm=a2g0o.productlist.main.53.723d9YJf9YJfsh&algo_pvid=3384e824-249e-42d6-87a5-6255d528aa1d&algo_exp_id=3384e824-249e-42d6-87a5-6255d528aa1d-52&pdp_ext_f=%7B%22order%22%3A%224%22%2C%22eval%22%3A%221%22%2C%22fromPage%22%3A%22search%22%7D&pdp_npi=6%40dis%21PYG%21178896%21178896%21%21%21195.63%21195.63%21%40212e509017812840859386959ee390%2112000056426968239%21sea%21PY%21102069714%21X%211%210%21n_tag%3A-29919%3Bd%3Ad06c9a5b%3Bm03_new_user%3A-29895&curPageLogUid=XLb1nPunHBlM&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005011747660895%7C_p_origin_prod%3A', 'tapa frascos ', 'Productos de Reventa', ARRAY[], TRUE, '2026-06-26T06:30:22.570Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (31, 'https://www.amazon.com/-/es/Don-Quijote-Mancha-Edici%C3%B3n-anotada/dp/9378714749/ref=tmm_hrd_swatch_0', 'libro don quijote', 'Personal', ARRAY[], TRUE, '2026-06-26T06:31:10.115Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (32, 'https://21st.dev/community/components', 'slides, hero para webs animadas', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:36:33.499Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (37, 'https://www.youtube.com/watch?v=zkkKz9SKhqU&t=1s', 'Pelicula Buscando la Verdad', 'Personal', ARRAY[], TRUE, '2026-06-26T22:23:03.527Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (40, 'https://www.youtube.com/watch?v=BiHiNCrC8i4&list=PL0eBi5Iq-u8fvBovJMHu5EYgXlyjbGRWk', 'historia relato para nix', 'CONTENIDO_YOUTUBE', ARRAY[], TRUE, '2026-06-26T23:34:19.204Z', 16, 19);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (39, 'https://www.youtube.com/watch?v=CuasajuIBUU', 'Caso paranormal mexico', 'CONTENIDO_YOUTUBE', ARRAY[], TRUE, '2026-06-26T22:24:48.870Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (38, 'https://www.youtube.com/watch?v=-UbmJEtUQYU', 'Relato historias ', 'CONTENIDO_YOUTUBE', ARRAY[], TRUE, '2026-06-26T22:23:36.843Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (36, 'https://podcast.adobe.com/en/enhance', 'Adobe Podcast eliminar mejorar audios, elimina sonidos de fondo de audios', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T07:04:57.528Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (35, 'https://developer.mozilla.org/en-US/observatory/analyze?host=missyteen.com', 'escanear webs para velocidad y seguridad', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:40:31.329Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (34, 'https://docs.google.com/spreadsheets/d/1Po2Z5Be_n9I_oEOBZgZYAH6ufx20LOrBNsNF5ZokUKs/edit?gid=0#gid=0', 'inventario equipos Ronald', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:39:30.459Z', 16, NULL);
INSERT INTO "enlaces" ("id", "url", "descripcion", "categoria", "etiquetas", "funciona", "creado_en", "proyecto_id", "entidad_id") VALUES (33, 'https://docs.google.com/spreadsheets/d/1LdyM_GsTCymY68gdM3XJ5XR9ByWAYm7t/edit?gid=637530588#gid=637530588', 'presupuesto 2026 - formato', 'HERRAMIENTAS', ARRAY[], TRUE, '2026-06-26T06:39:08.861Z', 16, NULL);
SELECT setval(pg_get_serial_sequence('"enlaces"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "enlaces";

-- Datos para la tabla: finanzas (14 registros)
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (13, 4, 'vencimiento_cliente', '500000.00', 'Cliente: Jordan - Renovación anual de dominio y hosting', 'pendiente', '0.00', '2026-12-05T03:00:00.000Z', '2026-06-13T11:44:12.620Z', NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (21, 18, 'vencimiento_cliente', '1500000.00', 'Blue one Trade - Renovacion anual de hosting, soporte técnico', 'PENDIENTE', '1500000.00', '2026-10-03T03:00:00.000Z', '2026-07-07T09:31:38.048Z', NULL, 'ANUAL', TRUE, 10, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (14, 4, 'vencimiento_cliente', '1150000.00', 'Saldo del 50% por venta de PC (Dario Ovelar)', 'pagado', '0.00', '2026-06-26T03:00:00.000Z', '2026-06-13T11:44:12.620Z', NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (16, 17, 'egreso', '350000.00', 'Bauel Top Correos Coporativos', 'PENDIENTE', '350000.00', '2026-08-11T03:00:00.000Z', '2026-07-05T09:39:34.564Z', 11, 'MENSUAL', TRUE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (19, 18, 'vencimiento_cliente', '2200000.00', 'Renovación anual hosting, dominio, soporte técnico, actualizaciones  y correos corporativos webmail', 'PENDIENTE', '2200000.00', '2027-03-15T03:00:00.000Z', '2026-07-05T11:00:08.637Z', NULL, 'ANUAL', TRUE, 3, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (12, 4, 'vencimiento_cliente', '500000.00', 'Cliente: Jordan - Posicionamiento SEO (cuota 3/3)', 'PAGADO', '0.00', '2026-07-23T03:00:00.000Z', '2026-06-13T11:44:12.620Z', NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (22, 22, 'vencimiento_cliente', '550000.00', 'Renovacion anual de correos, hosting, dominio y soporte técnico', 'PENDIENTE', '550000.00', '2027-02-08T03:00:00.000Z', '2026-07-07T19:04:42.059Z', NULL, 'ANUAL', TRUE, 2, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (20, 18, 'vencimiento_cliente', '1500000.00', 'BNF US - Renovación anual de hosting, soporte técnico', 'PENDIENTE', '1500000.00', '2026-08-07T03:00:00.000Z', '2026-07-07T09:28:03.896Z', NULL, 'ANUAL', TRUE, 8, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (23, 23, 'vencimiento_cliente', '15400000.00', 'Renovacion anual de correos Gmail Workspace, hosting, dominio y soporte técnico', 'PENDIENTE', '15400000.00', '2026-12-10T03:00:00.000Z', '2026-07-07T19:09:31.236Z', NULL, 'ANUAL', TRUE, 12, NULL, NULL, 14, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (25, 25, 'vencimiento_cliente', '2200000.00', 'Renovacion de Dominio, hosting, correos webmail y soporte técnico', 'PENDIENTE', '2200000.00', '2027-05-25T03:00:00.000Z', '2026-07-08T03:38:14.816Z', NULL, 'ANUAL', TRUE, 5, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (15, 17, 'egreso', '180000.00', 'HyGSA google workspace correos corporativos 3 cuentas activas', 'PENDIENTE', '180000.00', '2026-08-01T03:00:00.000Z', '2026-07-05T09:38:52.278Z', 1, 'MENSUAL', TRUE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (11, 4, 'vencimiento_cliente', '500000.00', 'Sistema de gestión', 'PENDIENTE', '0.00', '2026-07-05T03:00:00.000Z', '2026-06-13T11:44:12.620Z', NULL, NULL, FALSE, NULL, NULL, NULL, 14, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (26, 26, 'vencimiento_cliente', '3978000.00', 'Renovacion anual de correos Gmail Workspace, hosting, dominio y soporte técnico', 'PENDIENTE', '3978000.00', '2027-05-19T03:00:00.000Z', '2026-07-08T03:47:21.768Z', NULL, 'ANUAL', TRUE, 5, NULL, NULL, NULL, NULL);
INSERT INTO "finanzas" ("id", "proyecto_id", "tipo", "monto", "descripcion", "estado_pago", "saldo_pendiente", "fecha_vencimiento", "fecha_transaccion", "dia_vencimiento", "frecuencia", "recurrente", "mes_vencimiento", "cuota_actual", "cuotas_total", "entidad_origen_id", "entidad_id") VALUES (28, 27, 'vencimiento_cliente', '600000.00', 'Cobrar por renovación de dominio, hosting y correo webmail', 'PENDIENTE', '600000.00', '2026-07-01T03:00:00.000Z', '2026-07-08T06:41:27.455Z', NULL, 'ANUAL', TRUE, 7, NULL, NULL, NULL, NULL);
SELECT setval(pg_get_serial_sequence('"finanzas"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "finanzas";

-- Datos para la tabla: proyectos (12 registros)
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (26, 'HYG S.A.', NULL, '{"estado":"ACTIVO"}'::jsonb, '2026-07-08T03:45:43.032Z', 16, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (27, 'HOSTING, DOMINIO, WEBMAIL', NULL, '{"estado":"ACTIVO"}'::jsonb, '2026-07-08T06:19:02.914Z', 22, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (16, 'LINKS', 'Link de utilidades, enlaces a servicios, links de proyectos y tutoriales', '{"estado":"ACTIVO"}'::jsonb, '2026-06-26T04:32:41.191Z', 11, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (18, 'WEBSITE CORPORATIVO', NULL, '{"estado":"CULMINADO"}'::jsonb, '2026-07-05T10:58:33.200Z', 21, 'CULMINADO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (19, 'VIDEOS PARA YOUTUBE', 'estructura de videos y nuevas ideas, pruebas, implementaciones', '{"estado":"ACTIVO"}'::jsonb, '2026-07-07T00:05:46.428Z', 19, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (20, 'BNF US', 'website corporativo, hosting, dominio, correos', '{"estado":"ACTIVO"}'::jsonb, '2026-07-07T09:26:32.343Z', 21, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (21, 'BLUE ON TRADE', 'Creacion de Website, Hosting, soporte técnico', '{"estado":"ACTIVO"}'::jsonb, '2026-07-07T09:30:54.749Z', 21, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (17, 'URGENTES TAREAS', NULL, '{"estado":"ACTIVO"}'::jsonb, '2026-06-26T06:42:26.736Z', 14, 'ACTIVO', NULL, NULL, NULL, TRUE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (22, 'TÑR MEDICAL', 'Website, hosting y correos. Dominio pagan ellos', '{"estado":"ACTIVO"}'::jsonb, '2026-07-07T19:02:48.571Z', 14, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (23, 'WEBSITE, CORREOS', 'Renovacion anual de correos coporativos, hosting, dominio y soporte técnico', '{"estado":"ACTIVO"}'::jsonb, '2026-07-07T19:08:02.922Z', 16, 'ACTIVO', NULL, NULL, NULL, FALSE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (4, 'JORDAN LABORATORIO COMMON RAIL', 'Jordan Laboratorio Common Rail', '{"estado":"ACTIVO"}'::jsonb, '2026-06-13T10:48:46.627Z', 12, 'ACTIVO', NULL, NULL, NULL, TRUE);
INSERT INTO "proyectos" ("id", "nombre", "descripcion", "metadatos", "fecha_creacion", "entidad_id", "estado", "fecha_fin", "fecha_inicio", "notas", "is_destacado") VALUES (25, 'ADECOMI', 'Website, hosting, dominio y correos webmail', '{"estado":"ACTIVO"}'::jsonb, '2026-07-08T03:36:57.983Z', 21, 'ACTIVO', NULL, NULL, NULL, FALSE);
SELECT setval(pg_get_serial_sequence('"proyectos"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "proyectos";

-- Datos para la tabla: tareas (27 registros)
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (2, 17, 'preguntar a luis león lo de nina y sami', 'PENDIENTE', 'media', NULL, '2026-06-26T06:44:42.745Z', '2026-06-26T06:44:42.745Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (3, 17, 'Lampara usb para mama', 'PENDIENTE', 'media', NULL, '2026-06-26T06:45:22.007Z', '2026-06-26T06:45:22.007Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (4, 17, 'ODONTOLOGÍA, reparación completa a cuotas', 'PENDIENTE', 'alta', NULL, '2026-06-26T06:45:49.187Z', '2026-06-26T06:45:49.187Z', NULL, TRUE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (9, 17, 'actualizar permiso en el sistema de matias para cargar productos', 'CULMINADO', 'media', NULL, '2026-06-26T08:45:02.782Z', '2026-06-26T08:45:48.987Z', NULL, TRUE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (10, 17, 'CPF brasil, partida de nacimiento, cédula, pasaporte. ', 'PENDIENTE', 'alta', NULL, '2026-06-26T09:40:43.772Z', '2026-06-26T09:40:43.772Z', NULL, TRUE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (11, 17, 'Cartelería con Dario y Fabi', 'PENDIENTE', 'media', NULL, '2026-06-26T10:10:14.458Z', '2026-06-26T10:10:14.458Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (12, 17, 'citol para ojos', 'PENDIENTE', 'media', NULL, '2026-06-26T10:10:46.586Z', '2026-06-26T10:10:46.586Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (14, 17, 'Publicar cuchillos', 'PENDIENTE', 'media', NULL, '2026-06-26T10:12:20.974Z', '2026-06-26T10:12:20.974Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (15, 17, 'Publicar mouse pads (2)', 'PENDIENTE', 'media', NULL, '2026-06-26T10:12:34.655Z', '2026-06-26T10:12:34.655Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (16, 17, 'Culminar video de nix cronicas 1 español', 'PENDIENTE', 'media', NULL, '2026-06-26T10:13:05.947Z', '2026-06-26T10:13:05.947Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (17, 17, 'Enviar reporte del sistema a Jordan - Update 6', 'CULMINADO', 'media', NULL, '2026-06-26T22:01:06.502Z', '2026-06-26T22:01:22.198Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (18, 17, 'Comprar Cintillos medianos 5 y chicos 5', 'PENDIENTE', 'media', NULL, '2026-06-26T22:02:24.683Z', '2026-06-26T22:02:24.683Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (19, 17, 'Citol para ojos comprar', 'PENDIENTE', 'media', NULL, '2026-06-26T22:03:00.112Z', '2026-06-26T22:03:00.112Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (20, 17, 'mandar lavar calzado colcci', 'PENDIENTE', 'media', NULL, '2026-06-26T22:03:19.513Z', '2026-06-26T22:03:19.513Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (21, 17, 'hotmart ver curso de cerveza artesanal para subir', 'PENDIENTE', 'media', NULL, '2026-06-26T22:03:34.054Z', '2026-06-26T22:03:34.054Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (22, 17, 'Crear 2 primeros videos de perfumes héroes (Homelander y Soldier Boy)', 'PENDIENTE', 'media', NULL, '2026-06-26T22:04:26.893Z', '2026-06-26T22:04:26.893Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (23, 17, 'Aplicar recapcha en todas las webs, en acv ya está implementado', 'PENDIENTE', 'media', NULL, '2026-06-26T22:04:45.659Z', '2026-06-26T22:04:45.659Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (24, 17, 'Ronald tema de publicidad de Cino Luxe en EXA CNNU', 'CULMINADO', 'media', NULL, '2026-06-26T22:18:13.477Z', '2026-07-05T01:33:58.284Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (25, 17, 'ver perfume CK con looper tema de envio a asunción a domicilio y costo', 'PENDIENTE', 'media', NULL, '2026-07-05T07:20:57.847Z', '2026-07-05T07:20:57.847Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (26, 17, 'Cementerio con Pablito y necrópolis - martes', 'SEGUIMIENTO', 'media', NULL, '2026-07-05T07:56:24.740Z', '2026-07-05T07:56:35.665Z', NULL, TRUE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (13, 17, 'pago de hygsa correos verificar vence 02-07', 'CULMINADO', 'alta', '2026-07-01T03:00:00.000Z', '2026-06-26T10:11:45.485Z', '2026-07-05T09:20:27.956Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (27, 19, 'Creación de miniatura con letra amarilla en español', 'PENDIENTE', 'media', NULL, '2026-07-07T00:07:35.730Z', '2026-07-07T00:07:35.730Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (28, 19, 'Creación de miniatura con letra amarilla en portugués', 'PENDIENTE', 'media', NULL, '2026-07-07T00:07:50.212Z', '2026-07-07T00:07:50.212Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (29, 19, 'Creación de miniatura con letra amarilla en ingles', 'PENDIENTE', 'media', NULL, '2026-07-07T00:07:59.672Z', '2026-07-07T00:07:59.672Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (30, 19, 'video en ingles, creación de audio con IA', 'PENDIENTE', 'media', NULL, '2026-07-07T00:08:46.911Z', '2026-07-07T00:08:46.911Z', NULL, FALSE, NULL);
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (31, 19, 'Frase de inicio', 'PENDIENTE', 'media', NULL, '2026-07-07T00:18:52.942Z', '2026-07-07T00:59:33.154Z', NULL, FALSE, 'Definir la frase de inicio. 
Opciones actuales son:
1. Te dejo el perro y me llevo al gato jajaja
2. me llevo la torta y te dejo la silla ja ja ja ja
3.  ');
INSERT INTO "tareas" ("id", "proyecto_id", "descripcion", "estado", "prioridad", "fecha_limite", "fecha_creacion", "fecha_actualizacion", "finanza_id", "urgente", "notas") VALUES (32, 19, 'video de fondo para cada caso tratar de difuminar con gausiano', 'PENDIENTE', 'media', NULL, '2026-07-07T20:22:57.417Z', '2026-07-07T20:22:57.417Z', NULL, FALSE, NULL);
SELECT setval(pg_get_serial_sequence('"tareas"', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM "tareas";

-- Reactivar verificación de llaves foráneas
SET session_replication_role = 'origin';
