version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cerebro_db
    restart: always
    environment:
      POSTGRES_USER: admin_cerebro
      POSTGRES_PASSWORD: TuPasswordSeguro123 # Cambia esto por la contraseña que quieras
      POSTGRES_DB: segundo_cerebro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cerebro_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cerebro.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: